> 모델 학습하기 전에 모델이 잘 학습할 수 있도록 feature를 생성하는 방법

In [3]:
# 새로운 feature를 생성하는 방법

import numpy as np
import pandas as pd

df = pd.read_csv('/content/Titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# 데이터 탐색(EDA)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# Cleaning

In [5]:
# 결측치 cleaning
(df.isnull().sum()/ len(df)).sort_values(ascending=False)

Cabin          0.771044
Age            0.198653
Embarked       0.002245
PassengerId    0.000000
Name           0.000000
Pclass         0.000000
Survived       0.000000
Sex            0.000000
Parch          0.000000
SibSp          0.000000
Fare           0.000000
Ticket         0.000000
dtype: float64

In [6]:
# Embarked
df['Embarked'].value_counts() # 각 데이터별 수

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [7]:
embarked_mode = df['Embarked'].mode().values[0] # 최빈값
embarked_mode

'S'

In [8]:
df["Embarked"].fillna(embarked_mode, inplace=True)

df['Embarked'].isnull().sum()

/tmp/ipykernel_452/3532690098.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Embarked"].fillna(embarked_mode, inplace=True)

np.int64(0)

In [9]:
# Age
df['Age'].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [10]:
age_mean = df['Age'].mean() #스칼라
age_mean

np.float64(29.69911764705882)

In [11]:
df['Age'].fillna(age_mean, inplace=True)
df['Age'].isnull().sum()

/tmp/ipykernel_452/111359174.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(age_mean, inplace=True)

np.int64(0)

In [12]:
# Cabin
df['is_cabin'] = df['Cabin'].map(lambda x:0 if pd.isnull(x) else 1)

df[['is_cabin', 'Cabin']].head()

   is_cabin Cabin
0         0   NaN
1         1   C85
2         0   NaN
3         1  C123
4         0   NaN

In [13]:
df.drop(columns=['Cabin'], inplace =True)

df.isnull().sum().sum()

np.int64(0)

In [14]:
print(f"before : {df.shape}")
df.drop_duplicates(inplace=True) # row 중복 제거
print(f"after : {df.shape}")

before : (891, 12)
after : (891, 12)

# Feature 생성하자

In [15]:
df.columns = [col.lower() for col in df.columns]

In [16]:
df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,is_cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0

In [17]:
df["passengerid"].nunique() == df.shape[0]

True

In [18]:
df.shape #(전체 데이터, 전체 변수)

(891, 12)

In [19]:
df.set_index(['passengerid'], inplace=True)
df.head(10)

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,is_cabin
passengerid,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,S,0
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C,1
3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S,0
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S,1
5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,S,0
6,0,3,"Moran, Mr. James",male,29.699118,0,0,330877,8.4583,Q,0
7,0,1,"McCarthy, Mr. Timothy J",male,54.000000,0,0,17463,51.8625,S,1
8,0,3,"Palsson, Master. Gosta Leonard",male,2.000000,3,1,349909,21.0750,S,0
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.000000,0,2,347742,11.1333,S,0
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.000000,1,0,237736,30.0708,C,0

> 전체 데이터에서 train과 test를 나누는 기준은 무엇인가<br>
> if 전체 데이터가 충분히 많으면 train : test = 7: 3<br>
> if 전체 데이터가 충분하지 않으면 train : test = 9: 1<br>
> if 평가 데이터를 충분히 정말 충분히 얻을 수 없다면...<br>
> 기억하자!! test의 비율을 낮출 수록 당연히 모델의 퀄리티는 다운된다.

In [20]:
from sklearn.model_selection import  train_test_split

train, test = train_test_split(df, test_size=0.18)

train.shape, test.shape

((730, 11), (161, 11))

In [22]:
train.reset_index(drop = True, inplace = True)
test.reset_index(drop = True, inplace = True)

# Feature Extraction

In [23]:
train.head()

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,is_cabin
0,0,3,"Sivic, Mr. Husein",male,40.0,0,0,349251,7.8958,S,0
1,1,3,"Sundman, Mr. Johan Julian",male,44.0,0,0,STON/O 2. 3101269,7.9250,S,0
2,0,3,"Beavan, Mr. William Thomas",male,19.0,0,0,323951,8.0500,S,0
3,0,3,"Elias, Mr. Joseph Jr",male,17.0,1,1,2690,7.2292,C,0
4,0,3,"Barbara, Mrs. (Catherine David)",female,45.0,0,1,2691,14.4542,C,0

In [24]:
df_number = train.select_dtypes(np.number)
df_number.columns

Index(['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare', 'is_cabin'], dtype='object')

In [25]:
df_number.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  730 non-null    int64
 1   pclass    730 non-null    int64
 2   age       730 non-null    float64
 3   sibsp     730 non-null    int64
 4   parch     730 non-null    int64
 5   fare      730 non-null    float64
 6   is_cabin  730 non-null    int64
dtypes: float64(2), int64(5)
memory usage: 40.1 KB

In [28]:
df_number['survived'] = df_number['survived'].astype('int32')
df_number['pclass'] = df_number['pclass'].astype('int32')
df_number['age'] = df_number['age'].astype('float32')
df_number['is_cabin'] = df_number['is_cabin'].astype('float32')

df_number.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  730 non-null    int32
 1   pclass    730 non-null    int32
 2   age       730 non-null    float32
 3   sibsp     730 non-null    int64
 4   parch     730 non-null    int64
 5   fare      730 non-null    float64
 6   is_cabin  730 non-null    float32
dtypes: float32(2), float64(1), int32(2), int64(2)
memory usage: 28.6 KB

In [31]:

train['survived'] = train['survived'].astype('int32')
train['pclass'] = train['pclass'].astype('int32')
train['age'] = train['age'].astype('float32')
train['is_cabin'] = train['is_cabin'].astype('float32')

test['survived'] = test['survived'].astype('int32')
test['pclass'] = test['pclass'].astype('int32')
test['age'] = test['age'].astype('float32')
test['is_cabin'] = test['is_cabin'].astype('float32')

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  730 non-null    int32
 1   pclass    730 non-null    int32
 2   name      730 non-null    object
 3   sex       730 non-null    object
 4   age       730 non-null    float32
 5   sibsp     730 non-null    int64
 6   parch     730 non-null    int64
 7   ticket    730 non-null    object
 8   fare      730 non-null    float64
 9   embarked  730 non-null    object
 10  is_cabin  730 non-null    float32
dtypes: float32(2), float64(1), int32(2), int64(2), object(4)
memory usage: 51.5+ KB

In [32]:
# 절대 test를 보지 말아야함
train['name'].head()

0                  Sivic, Mr. Husein
1          Sundman, Mr. Johan Julian
2         Beavan, Mr. William Thomas
3               Elias, Mr. Joseph Jr
4    Barbara, Mrs. (Catherine David)
Name: name, dtype: object

In [34]:
train['name'] = train['name'].map(lambda x: x.strip())
test['name'] = test['name'].map(lambda x: x.strip())

train['name'].head()

0                  Sivic, Mr. Husein
1          Sundman, Mr. Johan Julian
2         Beavan, Mr. William Thomas
3               Elias, Mr. Joseph Jr
4    Barbara, Mrs. (Catherine David)
Name: name, dtype: object

In [35]:
"Mr." in "Sivic, Mr. Husein"

True

In [39]:
dict_designation = {
    'Mr.': '남성',
    'Master.': '남성',
    'Sir.': '남성',
    'Miss.': '미혼 여성',
    'Mrs.': '기혼 여성',
    'Ms.': '미혼/기혼 여성',
    'Lady.': '숙녀',
    'Mlle.': '아가씨',
    # 직업
    'Dr.': '의사',
    'Rev.': '목사',
    'Major.': '계급',
    'Don.': '교수',
    'Col.': '군인',
    'Capt.': '군인',
    # 귀족
    'Mme.': '영부인',
    'Countess.': '백작부인',
    'Jonkheer.': '귀족'
}

In [41]:
def add_designation(name):
  #초기값
  result = "unknown"                  # 정의된 호칭이 없는 때, 모름(unknown)
  for key in dict_designation.keys(): # 정의된 호칭 정보들
    if key in name:                   # 만약, 사용자 이름에 호칭이 있다면,
      result = dict_designation[key]  # 해당 호칭 한국어명 리턴
      break
  return result

train['designation'] = train['name'].map(lambda x: add_designation(x))
test['designation'] = test['name'].map(lambda x: add_designation(x))

train[['name','designation']].head(100)

                               name designation
0                 Sivic, Mr. Husein          남성
1         Sundman, Mr. Johan Julian          남성
2        Beavan, Mr. William Thomas          남성
3              Elias, Mr. Joseph Jr          남성
4   Barbara, Mrs. (Catherine David)       기혼 여성
..                              ...         ...
95          Chapman, Mr. John Henry          남성
96       Collander, Mr. Erik Gustaf          남성
97    Somerton, Mr. Francis William          남성
98     Rush, Mr. Alfred George John          남성
99               Giglio, Mr. Victor          남성

[100 rows x 2 columns]