In [1]:
# 새로운 feature를 생성하는 방법

import numpy as np
import pandas as pd

df = pd.read_csv('/content/cinemaTicket_Ref.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142524 entries, 0 to 142523
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   film_code     142524 non-null  int64
 1   cinema_code   142524 non-null  int64
 2   total_sales   142524 non-null  int64
 3   tickets_sold  142524 non-null  int64
 4   tickets_out   142524 non-null  int64
 5   show_time     142524 non-null  int64
 6   occu_perc     142399 non-null  float64
 7   ticket_price  142524 non-null  float64
 8   ticket_use    142524 non-null  int64
 9   capacity      142399 non-null  float64
 10  date          142524 non-null  object
 11  month         142524 non-null  int64
 12  quarter       142524 non-null  int64
 13  day           142524 non-null  int64
dtypes: float64(3), int64(10), object(1)
memory usage: 15.2+ MB

In [2]:
df['date'].head()

0    2018-05-05
1    2018-05-05
2    2018-05-05
3    2018-05-05
4    2018-05-05
Name: date, dtype: object

In [3]:
df['date'] = pd.to_datetime(df['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142524 entries, 0 to 142523
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   film_code     142524 non-null  int64
 1   cinema_code   142524 non-null  int64
 2   total_sales   142524 non-null  int64
 3   tickets_sold  142524 non-null  int64
 4   tickets_out   142524 non-null  int64
 5   show_time     142524 non-null  int64
 6   occu_perc     142399 non-null  float64
 7   ticket_price  142524 non-null  float64
 8   ticket_use    142524 non-null  int64
 9   capacity      142399 non-null  float64
 10  date          142524 non-null  datetime64[ns]
 11  month         142524 non-null  int64
 12  quarter       142524 non-null  int64
 13  day           142524 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(10)
memory usage: 15.2 MB

In [4]:
# weekday(요일): 월 ~ 일(0~6)
df['date'].dt.weekday.head()

0    5
1    5
2    5
3    5
4    5
Name: date, dtype: int32

In [5]:
# dayofyear : 연도기준으로 몇일째인지...
df['date'].dt.dayofyear.head()

0    125
1    125
2    125
3    125
4    125
Name: date, dtype: int32

# 진행바
> 프로그램(&모델 학습시간..)이 얼마나 진행되고 있는지 표시하는 라이브러리

In [6]:
from tqdm.auto import tqdm

In [7]:
i = 0
for j in tqdm(
    np.random.rand(100000000)
    , desc ="설명글", leave=False
    ):
  i = i**2

설명글:   0%|          | 0/100000000 [00:00<?, ?it/s]

In [8]:
import time

# outer => 진행바가 유지(leave =True)
for outer in tqdm([10,20,30,40,50], desc="outer", leave=True):
  # inner => 진행바가 유지(leave = False)
  for inner in tqdm(range(100), desc="inner", leave=False):
    time.sleep(0.01)

outer:   0%|          | 0/5 [00:00<?, ?it/s]

inner:   0%|          | 0/100 [00:00<?, ?it/s]

inner:   0%|          | 0/100 [00:00<?, ?it/s]

inner:   0%|          | 0/100 [00:00<?, ?it/s]

inner:   0%|          | 0/100 [00:00<?, ?it/s]

inner:   0%|          | 0/100 [00:00<?, ?it/s]